// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SpineWise_Web
{
    public partial class SpinewiseMLModel
    {
        /// <summary>
        /// model input class for SpinewiseMLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"UpperBackDistance")]
            public float UpperBackDistance { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"PressureSensor1")]
            public bool PressureSensor1 { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"PressureSensor2")]
            public bool PressureSensor2 { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"PressureSensor3")]
            public bool PressureSensor3 { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"PressureSensor4")]
            public bool PressureSensor4 { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Good")]
            public bool Good { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SpinewiseMLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"UpperBackDistance")]
            public float UpperBackDistance { get; set; }

            [ColumnName(@"PressureSensor1")]
            public float[] PressureSensor1 { get; set; }

            [ColumnName(@"PressureSensor2")]
            public float[] PressureSensor2 { get; set; }

            [ColumnName(@"PressureSensor3")]
            public float[] PressureSensor3 { get; set; }

            [ColumnName(@"PressureSensor4")]
            public float[] PressureSensor4 { get; set; }

            [ColumnName(@"Good")]
            public bool Good { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public bool PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

            [ColumnName(@"Probability")]
            public float Probability { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SpinewiseMLModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
